apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: repo_url
      value: {{body.pull_request.head.repo.ssh_url}}
    - name: git_revision
      value: {{revision}}
  pipelineSpec:
    params:
      - name: repo_url
      - name: git_revision
    workspaces:
      - name: source
      - name: ssh-directory
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory
        params:
          - name: depth
            value: "0"
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.git_revision)


  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ssh-directory
      secret:
        secretName: nordmart-api-ssh-creds
